/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperadminAuthRouteImport } from './routes/superadmin.auth'
import { Route as SchoolsSchoolIdRouteImport } from './routes/schools.$schoolId'
import { Route as SchoolAuthRouteImport } from './routes/school.auth'
import { Route as AppUpgradeRouteImport } from './routes/app.upgrade'
import { Route as AppTransfersRouteImport } from './routes/app.transfers'
import { Route as AppStaffRouteImport } from './routes/app.staff'
import { Route as AppSchoolsRouteImport } from './routes/app.schools'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMarksCaptureRouteImport } from './routes/app.marks-capture'
import { Route as AppMarksRouteImport } from './routes/app.marks'
import { Route as AppLinkRequestsRouteImport } from './routes/app.link-requests'
import { Route as AppLearnersRouteImport } from './routes/app.learners'
import { Route as AppExamTimetableRouteImport } from './routes/app.exam-timetable'
import { Route as AppDisciplineSchoolRouteImport } from './routes/app.discipline-school'
import { Route as AppDisciplineRouteImport } from './routes/app.discipline'
import { Route as AppClassesRouteImport } from './routes/app.classes'
import { Route as AppChildrenRouteImport } from './routes/app.children'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAttendanceCaptureRouteImport } from './routes/app.attendance-capture'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSchoolsRouteImport } from './routes/admin.schools'
import { Route as AdminDistrictsRouteImport } from './routes/admin.districts'
import { Route as AdminSchoolsSchoolIdRouteImport } from './routes/admin.schools.$schoolId'

const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperadminAuthRoute = SuperadminAuthRouteImport.update({
  id: '/superadmin/auth',
  path: '/superadmin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsSchoolIdRoute = SchoolsSchoolIdRouteImport.update({
  id: '/$schoolId',
  path: '/$schoolId',
  getParentRoute: () => SchoolsRoute,
} as any)
const SchoolAuthRoute = SchoolAuthRouteImport.update({
  id: '/school/auth',
  path: '/school/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSchoolsRoute = AppSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMarksCaptureRoute = AppMarksCaptureRouteImport.update({
  id: '/marks-capture',
  path: '/marks-capture',
  getParentRoute: () => AppRoute,
} as any)
const AppMarksRoute = AppMarksRouteImport.update({
  id: '/marks',
  path: '/marks',
  getParentRoute: () => AppRoute,
} as any)
const AppLinkRequestsRoute = AppLinkRequestsRouteImport.update({
  id: '/link-requests',
  path: '/link-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnersRoute = AppLearnersRouteImport.update({
  id: '/learners',
  path: '/learners',
  getParentRoute: () => AppRoute,
} as any)
const AppExamTimetableRoute = AppExamTimetableRouteImport.update({
  id: '/exam-timetable',
  path: '/exam-timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplineSchoolRoute = AppDisciplineSchoolRouteImport.update({
  id: '/discipline-school',
  path: '/discipline-school',
  getParentRoute: () => AppRoute,
} as any)
const AppDisciplineRoute = AppDisciplineRouteImport.update({
  id: '/discipline',
  path: '/discipline',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppChildrenRoute = AppChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceCaptureRoute = AppAttendanceCaptureRouteImport.update({
  id: '/attendance-capture',
  path: '/attendance-capture',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolsRoute = AdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDistrictsRoute = AdminDistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolsSchoolIdRoute = AdminSchoolsSchoolIdRouteImport.update({
  id: '/$schoolId',
  path: '/$schoolId',
  getParentRoute: () => AdminSchoolsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/schools': typeof SchoolsRouteWithChildren
  '/admin/districts': typeof AdminDistrictsRoute
  '/admin/schools': typeof AdminSchoolsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/attendance-capture': typeof AppAttendanceCaptureRoute
  '/app/audit': typeof AppAuditRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/children': typeof AppChildrenRoute
  '/app/classes': typeof AppClassesRoute
  '/app/discipline': typeof AppDisciplineRoute
  '/app/discipline-school': typeof AppDisciplineSchoolRoute
  '/app/exam-timetable': typeof AppExamTimetableRoute
  '/app/learners': typeof AppLearnersRoute
  '/app/link-requests': typeof AppLinkRequestsRoute
  '/app/marks': typeof AppMarksRoute
  '/app/marks-capture': typeof AppMarksCaptureRoute
  '/app/profile': typeof AppProfileRoute
  '/app/schools': typeof AppSchoolsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/school/auth': typeof SchoolAuthRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdRoute
  '/superadmin/auth': typeof SuperadminAuthRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/schools/$schoolId': typeof AdminSchoolsSchoolIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/schools': typeof SchoolsRouteWithChildren
  '/admin/districts': typeof AdminDistrictsRoute
  '/admin/schools': typeof AdminSchoolsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/attendance-capture': typeof AppAttendanceCaptureRoute
  '/app/audit': typeof AppAuditRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/children': typeof AppChildrenRoute
  '/app/classes': typeof AppClassesRoute
  '/app/discipline': typeof AppDisciplineRoute
  '/app/discipline-school': typeof AppDisciplineSchoolRoute
  '/app/exam-timetable': typeof AppExamTimetableRoute
  '/app/learners': typeof AppLearnersRoute
  '/app/link-requests': typeof AppLinkRequestsRoute
  '/app/marks': typeof AppMarksRoute
  '/app/marks-capture': typeof AppMarksCaptureRoute
  '/app/profile': typeof AppProfileRoute
  '/app/schools': typeof AppSchoolsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/school/auth': typeof SchoolAuthRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdRoute
  '/superadmin/auth': typeof SuperadminAuthRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/schools/$schoolId': typeof AdminSchoolsSchoolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/schools': typeof SchoolsRouteWithChildren
  '/admin/districts': typeof AdminDistrictsRoute
  '/admin/schools': typeof AdminSchoolsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/attendance-capture': typeof AppAttendanceCaptureRoute
  '/app/audit': typeof AppAuditRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/children': typeof AppChildrenRoute
  '/app/classes': typeof AppClassesRoute
  '/app/discipline': typeof AppDisciplineRoute
  '/app/discipline-school': typeof AppDisciplineSchoolRoute
  '/app/exam-timetable': typeof AppExamTimetableRoute
  '/app/learners': typeof AppLearnersRoute
  '/app/link-requests': typeof AppLinkRequestsRoute
  '/app/marks': typeof AppMarksRoute
  '/app/marks-capture': typeof AppMarksCaptureRoute
  '/app/profile': typeof AppProfileRoute
  '/app/schools': typeof AppSchoolsRoute
  '/app/staff': typeof AppStaffRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app/upgrade': typeof AppUpgradeRoute
  '/school/auth': typeof SchoolAuthRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdRoute
  '/superadmin/auth': typeof SuperadminAuthRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/schools/$schoolId': typeof AdminSchoolsSchoolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/auth'
    | '/pricing'
    | '/schools'
    | '/admin/districts'
    | '/admin/schools'
    | '/admin/users'
    | '/app/alerts'
    | '/app/assistant'
    | '/app/attendance'
    | '/app/attendance-capture'
    | '/app/audit'
    | '/app/calendar'
    | '/app/children'
    | '/app/classes'
    | '/app/discipline'
    | '/app/discipline-school'
    | '/app/exam-timetable'
    | '/app/learners'
    | '/app/link-requests'
    | '/app/marks'
    | '/app/marks-capture'
    | '/app/profile'
    | '/app/schools'
    | '/app/staff'
    | '/app/transfers'
    | '/app/upgrade'
    | '/school/auth'
    | '/schools/$schoolId'
    | '/superadmin/auth'
    | '/admin/'
    | '/app/'
    | '/admin/schools/$schoolId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/pricing'
    | '/schools'
    | '/admin/districts'
    | '/admin/schools'
    | '/admin/users'
    | '/app/alerts'
    | '/app/assistant'
    | '/app/attendance'
    | '/app/attendance-capture'
    | '/app/audit'
    | '/app/calendar'
    | '/app/children'
    | '/app/classes'
    | '/app/discipline'
    | '/app/discipline-school'
    | '/app/exam-timetable'
    | '/app/learners'
    | '/app/link-requests'
    | '/app/marks'
    | '/app/marks-capture'
    | '/app/profile'
    | '/app/schools'
    | '/app/staff'
    | '/app/transfers'
    | '/app/upgrade'
    | '/school/auth'
    | '/schools/$schoolId'
    | '/superadmin/auth'
    | '/admin'
    | '/app'
    | '/admin/schools/$schoolId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/auth'
    | '/pricing'
    | '/schools'
    | '/admin/districts'
    | '/admin/schools'
    | '/admin/users'
    | '/app/alerts'
    | '/app/assistant'
    | '/app/attendance'
    | '/app/attendance-capture'
    | '/app/audit'
    | '/app/calendar'
    | '/app/children'
    | '/app/classes'
    | '/app/discipline'
    | '/app/discipline-school'
    | '/app/exam-timetable'
    | '/app/learners'
    | '/app/link-requests'
    | '/app/marks'
    | '/app/marks-capture'
    | '/app/profile'
    | '/app/schools'
    | '/app/staff'
    | '/app/transfers'
    | '/app/upgrade'
    | '/school/auth'
    | '/schools/$schoolId'
    | '/superadmin/auth'
    | '/admin/'
    | '/app/'
    | '/admin/schools/$schoolId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  SchoolsRoute: typeof SchoolsRouteWithChildren
  SchoolAuthRoute: typeof SchoolAuthRoute
  SuperadminAuthRoute: typeof SuperadminAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/superadmin/auth': {
      id: '/superadmin/auth'
      path: '/superadmin/auth'
      fullPath: '/superadmin/auth'
      preLoaderRoute: typeof SuperadminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/$schoolId': {
      id: '/schools/$schoolId'
      path: '/$schoolId'
      fullPath: '/schools/$schoolId'
      preLoaderRoute: typeof SchoolsSchoolIdRouteImport
      parentRoute: typeof SchoolsRoute
    }
    '/school/auth': {
      id: '/school/auth'
      path: '/school/auth'
      fullPath: '/school/auth'
      preLoaderRoute: typeof SchoolAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upgrade': {
      id: '/app/upgrade'
      path: '/upgrade'
      fullPath: '/app/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transfers': {
      id: '/app/transfers'
      path: '/transfers'
      fullPath: '/app/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/staff': {
      id: '/app/staff'
      path: '/staff'
      fullPath: '/app/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schools': {
      id: '/app/schools'
      path: '/schools'
      fullPath: '/app/schools'
      preLoaderRoute: typeof AppSchoolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marks-capture': {
      id: '/app/marks-capture'
      path: '/marks-capture'
      fullPath: '/app/marks-capture'
      preLoaderRoute: typeof AppMarksCaptureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marks': {
      id: '/app/marks'
      path: '/marks'
      fullPath: '/app/marks'
      preLoaderRoute: typeof AppMarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/link-requests': {
      id: '/app/link-requests'
      path: '/link-requests'
      fullPath: '/app/link-requests'
      preLoaderRoute: typeof AppLinkRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learners': {
      id: '/app/learners'
      path: '/learners'
      fullPath: '/app/learners'
      preLoaderRoute: typeof AppLearnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exam-timetable': {
      id: '/app/exam-timetable'
      path: '/exam-timetable'
      fullPath: '/app/exam-timetable'
      preLoaderRoute: typeof AppExamTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discipline-school': {
      id: '/app/discipline-school'
      path: '/discipline-school'
      fullPath: '/app/discipline-school'
      preLoaderRoute: typeof AppDisciplineSchoolRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discipline': {
      id: '/app/discipline'
      path: '/discipline'
      fullPath: '/app/discipline'
      preLoaderRoute: typeof AppDisciplineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classes': {
      id: '/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/children': {
      id: '/app/children'
      path: '/children'
      fullPath: '/app/children'
      preLoaderRoute: typeof AppChildrenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance-capture': {
      id: '/app/attendance-capture'
      path: '/attendance-capture'
      fullPath: '/app/attendance-capture'
      preLoaderRoute: typeof AppAttendanceCaptureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schools': {
      id: '/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AdminSchoolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/districts': {
      id: '/admin/districts'
      path: '/districts'
      fullPath: '/admin/districts'
      preLoaderRoute: typeof AdminDistrictsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schools/$schoolId': {
      id: '/admin/schools/$schoolId'
      path: '/$schoolId'
      fullPath: '/admin/schools/$schoolId'
      preLoaderRoute: typeof AdminSchoolsSchoolIdRouteImport
      parentRoute: typeof AdminSchoolsRoute
    }
  }
}

interface AdminSchoolsRouteChildren {
  AdminSchoolsSchoolIdRoute: typeof AdminSchoolsSchoolIdRoute
}

const AdminSchoolsRouteChildren: AdminSchoolsRouteChildren = {
  AdminSchoolsSchoolIdRoute: AdminSchoolsSchoolIdRoute,
}

const AdminSchoolsRouteWithChildren = AdminSchoolsRoute._addFileChildren(
  AdminSchoolsRouteChildren,
)

interface AdminRouteChildren {
  AdminDistrictsRoute: typeof AdminDistrictsRoute
  AdminSchoolsRoute: typeof AdminSchoolsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDistrictsRoute: AdminDistrictsRoute,
  AdminSchoolsRoute: AdminSchoolsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAttendanceCaptureRoute: typeof AppAttendanceCaptureRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChildrenRoute: typeof AppChildrenRoute
  AppClassesRoute: typeof AppClassesRoute
  AppDisciplineRoute: typeof AppDisciplineRoute
  AppDisciplineSchoolRoute: typeof AppDisciplineSchoolRoute
  AppExamTimetableRoute: typeof AppExamTimetableRoute
  AppLearnersRoute: typeof AppLearnersRoute
  AppLinkRequestsRoute: typeof AppLinkRequestsRoute
  AppMarksRoute: typeof AppMarksRoute
  AppMarksCaptureRoute: typeof AppMarksCaptureRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSchoolsRoute: typeof AppSchoolsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppAttendanceCaptureRoute: AppAttendanceCaptureRoute,
  AppAuditRoute: AppAuditRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChildrenRoute: AppChildrenRoute,
  AppClassesRoute: AppClassesRoute,
  AppDisciplineRoute: AppDisciplineRoute,
  AppDisciplineSchoolRoute: AppDisciplineSchoolRoute,
  AppExamTimetableRoute: AppExamTimetableRoute,
  AppLearnersRoute: AppLearnersRoute,
  AppLinkRequestsRoute: AppLinkRequestsRoute,
  AppMarksRoute: AppMarksRoute,
  AppMarksCaptureRoute: AppMarksCaptureRoute,
  AppProfileRoute: AppProfileRoute,
  AppSchoolsRoute: AppSchoolsRoute,
  AppStaffRoute: AppStaffRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SchoolsRouteChildren {
  SchoolsSchoolIdRoute: typeof SchoolsSchoolIdRoute
}

const SchoolsRouteChildren: SchoolsRouteChildren = {
  SchoolsSchoolIdRoute: SchoolsSchoolIdRoute,
}

const SchoolsRouteWithChildren =
  SchoolsRoute._addFileChildren(SchoolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  SchoolsRoute: SchoolsRouteWithChildren,
  SchoolAuthRoute: SchoolAuthRoute,
  SuperadminAuthRoute: SuperadminAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
